// <auto-generated />
using System;
using Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AnalyzerDbContext))]
    [Migration("20250628131004_CriacaoCotacao_CotacaoItem")]
    partial class CriacaoCotacao_CotacaoItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CWCotacao", b =>
                {
                    b.Property<int>("nCdCotacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdCotacao"));

                    b.Property<bool>("bFlFreteIncluso")
                        .HasColumnType("boolean");

                    b.Property<decimal>("dVlTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sDsCotacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("tDtCotacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("nCdCotacao");

                    b.ToTable("COTACAO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWCotacaoItem", b =>
                {
                    b.Property<int>("nCdCotacaoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdCotacaoItem"));

                    b.Property<decimal>("dVlProposto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("nCdCotacao")
                        .HasColumnType("integer");

                    b.Property<int>("nCdProduto")
                        .HasColumnType("integer");

                    b.Property<int>("nPrazoEntrega")
                        .HasColumnType("integer");

                    b.Property<int>("nSequencial")
                        .HasColumnType("integer");

                    b.HasKey("nCdCotacaoItem");

                    b.HasIndex("nCdCotacao");

                    b.HasIndex("nCdProduto");

                    b.ToTable("COTACAO_ITEM", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWProduto", b =>
                {
                    b.Property<int>("nCdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdProduto"));

                    b.Property<decimal>("dVlUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sCdProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("sNmProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("nCdProduto");

                    b.ToTable("PRODUTOS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWCotacaoItem", b =>
                {
                    b.HasOne("Domain.Entities.CWCotacao", "Cotacao")
                        .WithMany("lstCotacaoItem")
                        .HasForeignKey("nCdCotacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CWProduto", "Produto")
                        .WithMany()
                        .HasForeignKey("nCdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotacao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Domain.Entities.CWCotacao", b =>
                {
                    b.Navigation("lstCotacaoItem");
                });
#pragma warning restore 612, 618
        }
    }
}
